// client/src/components/AssortmentSection.tsx
import swimwearImg from "@assets/generated_images/swimwear_category_photo.png";
import lingerieImg from "@assets/generated_images/women's_lingerie_category.png";
import mensImg from "@assets/generated_images/men's_swimwear_category.png";
import kidsImg from "@assets/generated_images/children's_swimwear_category.png";
import poolImg from "@assets/generated_images/pool_accessories_category.png";
import beachImg from "@assets/generated_images/beach_clothing_category.png";

const categories = [
  { id: "1", name: "Купальники", image: swimwearImg },
  { id: "2", name: "Женское бельё", image: lingerieImg },
  { id: "3", name: "Мужские плавки и шорты", image: mensImg },
  { id: "4", name: "Детские купальники", image: kidsImg },
  { id: "5", name: "Для бассейна", image: poolImg },
  { id: "6", name: "Пляжная одежда", image: beachImg },
];

export default function AssortmentSection() {
  return (
    <section id="assortment" className="py-16 md:py-20 lg:py-24 bg-white">
      <div className="max-w-6xl mx-auto px-4 md:px-10 lg:px-16">
        <div className="text-center mb-12">
          <h2 className="font-serif text-3xl md:text-4xl font-medium text-[#1F1F1F] mb-4">
            Ассортимент
          </h2>
          <p className="text-[#7A7A7A] text-base md:text-lg max-w-2xl mx-auto">
            В нашем магазине представлен широкий выбор качественного белья и купальников
            для женщин, мужчин и детей
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 md:gap-8">
          {categories.map((category) => (
            <div key={category.id} className="group">
              <div className="aspect-square overflow-hidden rounded-2xl bg-[#FDE4EE] mb-4">
                <img src={category.image} alt={category.name} className="w-full h-full object-cover" />
              </div>
              <h3 className="text-center text-lg font-semibold text-[#1F1F1F]">
                {category.name}
              </h3>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

// src/components/AssortmentSection.vue
<script setup lang="ts">
import { RouterLink } from 'vue-router'
import swimwearImg from '@/assets/swimwear_category_photo.png'
import lingerieImg from "@/assets/women's_lingerie_category.png"
import mensImg from "@/assets/men's_swimwear_category.png"
import kidsImg from "@/assets/children's_swimwear_category.png"
import poolImg from '@/assets/pool_accessories_category.png'
import beachImg from '@/assets/beach_clothing_category.png'

const categories = [
  { id: '1', name: 'Купальники', image: swimwearImg, link: '/kupalniky' },
  { id: '2', name: 'Женское бельё', image: lingerieImg, link: null },
  { id: '3', name: 'Мужские плавки и шорты', image: mensImg, link: null },
  { id: '4', name: 'Детские купальники', image: kidsImg, link: null },
  { id: '5', name: 'Для бассейна', image: poolImg, link: null },
  { id: '6', name: 'Пляжная одежда', image: beachImg, link: null },
]
</script>

<template>
  <section id="assortment" class="py-16 md:py-20 lg:py-24 bg-white">
    <div class="max-w-6xl mx-auto px-4 md:px-10 lg:px-16">
      <div class="text-center mb-12">
        <h2 class="font-serif text-3xl md:text-4xl font-medium text-heading mb-4">
          Ассортимент магазина
        </h2>
        <p class="text-muted text-base md:text-lg max-w-2xl mx-auto">
          В нашем магазине представлен широкий выбор качественного белья и купальников
          для женщин, мужчин и детей
        </p>
      </div>

      <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 md:gap-8">
        <RouterLink
          v-for="category in categories"
          :key="category.id"
          :to="category.link || '#'"
          :class="[
            'group block',
            category.link ? 'cursor-pointer' : 'cursor-default pointer-events-none'
          ]"
        >
          <div class="aspect-square overflow-hidden rounded-2xl bg-primary-light mb-4 transition-transform duration-300 group-hover:scale-[1.02]">
            <img :src="category.image" :alt="category.name" class="w-full h-full object-cover" />
          </div>
          <h3 class="text-center text-lg font-semibold text-heading group-hover:text-primary transition-colors">
            {{ category.name }}
          </h3>
        </RouterLink>
      </div>
    </div>
  </section>
</template>
