// src/components/nizhnee-bele/HeroSection.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import heroImage from '@/assets/belyo/hero.png'

const isVisible = ref(false)

onMounted(() => {
  setTimeout(() => {
    isVisible.value = true
  }, 100)
})
</script>

<template>
  <section class="relative min-h-[600px] md:min-h-[700px] flex items-center">
    <div class="absolute inset-0">
      <img :src="heroImage" alt="Нижнее бельё" class="w-full h-full object-cover object-left" />
      <div class="absolute inset-0 bg-gradient-to-l from-black/35 via-black/15 to-transparent"></div>
    </div>
    <div class="relative z-10 w-full max-w-6xl mx-auto px-4 md:px-10 lg:px-16 py-32 flex justify-end">
      <div class="max-w-xl">
        <h1
          :class="[
            'font-serif text-4xl md:text-5xl lg:text-6xl font-medium text-white leading-tight mb-6 transition-all duration-700',
            isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'
          ]"
        >
          Нижнее бельё
        </h1>
        <p
          :class="[
            'text-white/90 text-lg md:text-xl leading-relaxed mb-8 transition-all duration-700 delay-100',
            isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'
          ]"
        >
          Индивидуальный подбор нижнего белья с учётом фигуры, посадки и комфорта. 
          Поможем выбрать модель, в которой вы будете чувствовать себя уверенно.
        </p>
        <div
          :class="[
            'flex flex-col sm:flex-row gap-4 transition-all duration-700 delay-200',
            isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'
          ]"
        >
          <a
            href="tel:+79218924860"
            class="bg-primary text-white rounded-full px-8 py-4 text-base font-medium hover:bg-primary/90 transition-colors inline-flex items-center justify-center gap-2"
          >
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
            </svg>
            Позвонить и подобрать бельё
          </a>
        </div>
      </div>
    </div>
  </section>
</template>

// client/src/components/HeroSection.tsx
import { useEffect, useState } from "react";
import heroImage from "@assets/generated_images/hero_swimwear_lifestyle_photo.png";

export default function HeroSection() {
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    setTimeout(() => setIsVisible(true), 100);
  }, []);

  return (
    <section id="home" className="min-h-screen flex items-center pt-20 pb-16 bg-[#FDF6F9]">
      <div className="max-w-6xl mx-auto px-4 md:px-10 lg:px-16 w-full">
        <div className="grid lg:grid-cols-2 gap-8 lg:gap-12 items-center">
          <div
            className={`order-2 lg:order-1 transition-all duration-700 ${
              isVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-8"
            }`}
          >
            <h1 className="font-serif text-4xl md:text-5xl lg:text-[48px] font-medium text-[#1F1F1F] leading-tight mb-6">
              Нижнее бельё
              <br />
              и купальники
              <br />
              <span className="italic text-[#F04C8B]">для всей семьи</span>
            </h1>
            <p className="text-[#3A3A3A] text-base md:text-lg leading-relaxed mb-8 max-w-md">
              Магазин с широким ассортиментом качественного нижнего белья и купальников.
              Профессиональная консультация и возможность примерки в уютной атмосфере.
            </p>
            <div className="flex flex-wrap items-center gap-4">
              <button
                onClick={() => document.getElementById("assortment")?.scrollIntoView({ behavior: "smooth" })}
                className="bg-[#F04C8B] text-white rounded-full px-8 py-4 text-base font-medium hover:bg-[#F04C8B]/90 transition-colors"
              >
                Смотреть ассортимент
              </button>
              <button
                onClick={() => document.getElementById("contacts")?.scrollIntoView({ behavior: "smooth" })}
                className="border border-[#F04C8B]/30 text-[#3A3A3A] rounded-full px-8 py-4 text-base hover:border-[#F04C8B] hover:text-[#F04C8B] transition-colors"
              >
                Как нас найти
              </button>
            </div>
          </div>

          <div
            className={`order-1 lg:order-2 flex justify-center lg:justify-end transition-all duration-1000 delay-200 ${
              isVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-8"
            }`}
          >
            <div className="relative animate-float">
              <img
                src={heroImage}
                alt="Модель в стильном купальнике"
                className="w-full max-w-sm lg:max-w-md rounded-[32px] shadow-2xl object-cover"
              />
              <div className="absolute -bottom-4 -left-4 bg-white rounded-2xl p-4 shadow-lg hidden md:block">
                <div className="text-2xl font-serif text-[#F04C8B]">500+</div>
                <div className="text-sm text-[#7A7A7A]">моделей в наличии</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
